project 'MapComponent.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MapComponent' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for MapComponent
  pod 'MJExtension', '~> 3.0.17'
  pod 'WeexSDK', '~> 0.24.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'BaiduMapKit', '~> 4.3.2'
  pod 'BMKLocationKit', '~> 1.6.0'
  pod 'SocketRocket', '0.4.2'
  
  target 'MapComponentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapComponentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
